[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'neoclide/coc.nvim'
merged = 0
rev = 'release'
hook_add = """
source ~/.config/nvim/coc.vim
"""

[[plugins]]
repo = 'kkiyama117/coc-toml'
depends = 'coc.nvim'

[[plugins]]
repo = 'junegunn/fzf'
merged = 0
build = './install --all'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
hook_add = """
source ~/.config/nvim/fzf.vim
"""

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-rhubarb'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'christianrondeau/vim-base64'

[[plugins]]
repo = 'Bakudankun/BackAndForward.vim'

[[plugins]]
repo = 'lambdalisue/gina.vim'

[[plugins]]
repo = 'morhetz/gruvbox'
hook_add = """
colorscheme gruvbox
"""

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = """
let g:airline#extensions#whitespace#enabled = 0
"""


[[plugins]]
repo = 'honza/vim-snippets'

[[plugins]]
repo = 'SirVer/ultisnips'
hook_add = """
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<tab>"
let g:UltiSnipsJumpBackwardTrigger="<s-tab>"
let g:UltiSnipsEditSplit="vertical"
nnoremap <leader>vu :<C-u>:UltiSnipsEdit<CR>
"""

[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = """
nmap <C-e> <Plug>(easymotion-overwin-f2)

command! E Explore
"""

[[plugins]]
repo = 'kburdett/vim-nuuid'

[[plugins]]
repo = 'preservim/nerdcommenter'

[[plugins]]
repo = 'junegunn/vim-peekaboo'
hook_add = """
let g:peekaboo_window="vert bo 60new"
"""

[[plugins]]
repo = 'Yilin-Yang/vim-markbar'
hook_add = """
let g:markbar_width = 60
"""
